// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./../views/components/Counter.vue')['default']
    DarkModeToggler: typeof import('./../views/components/DarkModeToggler.vue')['default']
    InertiaLink: typeof import('@inertiajs/inertia-vue3')['Link']
  }
}
