// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    InertiaLogo: typeof import('./../views/components/inertia-logo.vue')['default']
    LaravelLogo: typeof import('./../views/components/laravel-logo.vue')['default']
    ResourceBlock: typeof import('./../views/components/resource-block.vue')['default']
  }
}

export {}
