name: Main Worklow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Unit Test and Feature Test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'

      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Sqlite Database
        run: touch database/database.sqlite

      - name: Install PHP Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Bun
        run: curl https://bun.sh/install | bash

      - name: Install Node Dependencies
        run: /home/runner/.bun/bin/bun install

      - name: Laravel Test
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test -p

      - name: Vitest Test
        run: node_modules/.bin/vitest --coverage --run

  # deploy:
  #   name: Deploy via Laravel Forge
  #   runs-on: ubuntu-latest
  #   environment: production

  #   needs:
  #     - test

  #   steps:
  #     - uses: actions/checkout@v3.0.2
  #     - uses: jbrooksuk/laravel-forge-action@v1.0.2
  #       with:
  #         trigger_url: ${{ secrets.TRIGGER_URL }}
